---
repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.1
    hooks:
      - id: stylua-github

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-footnote
          - mdformat-tables
          - mdformat-toc

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix
